# Generated by Django 2.2.2 on 2019-07-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='date',
        ),
        migrations.AddField(
            model_name='idea',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, default='empty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='dateEdited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
