# Generated by Django 2.2.2 on 2019-07-18 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190717_2152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Idea',
        ),
    ]
