# Generated by Django 2.2.2 on 2019-07-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0003_delete_idea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateEdited', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=32)),
                ('idea', models.TextField()),
            ],
        ),
    ]
