# Generated by Django 2.2.2 on 2019-07-18 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_idea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='idea',
            new_name='content',
        ),
    ]
